# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
