# Generated by Django 2.2.9 on 2019-12-20 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testblog', '0002_auto_20191029_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
