# Generated by Django 2.2.9 on 2020-05-27 11:57

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trionyx', '0002_systemvariable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='changes',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='systemvariable',
            name='value',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='progress_output',
            field=jsonfield.fields.JSONField(default=list, verbose_name='Progress output'),
        ),
        migrations.AlterField(
            model_name='userattribute',
            name='value',
            field=jsonfield.fields.JSONField(),
        ),
    ]
