# Generated by Django 2.2.1 on 2019-06-01 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trionyx', '0002_auto_20190531_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
