# Generated by Django 2.2.1 on 2019-06-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trionyx', '0003_auto_20190601_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verbose_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
