# Generated by Django 2.2.1 on 2019-06-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trionyx', '0006_auto_20190614_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(blank=None, null=True),
        ),
    ]
