# Generated by Django 2.2.1 on 2019-10-13 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trionyx', '0007_user_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='object_verbose_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
