# Generated by Django 2.2.6 on 2019-10-27 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.encoder
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trionyx', '0009_auto_20191024_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('verbose_name', models.TextField(blank=True, default='', verbose_name='Verbose name')),
                ('celery_task_id', models.CharField(max_length=64, unique=True)),
                ('status', models.IntegerField(choices=[(10, 'Scheduled'), (20, 'Queue'), (30, 'Locked'), (40, 'Running'), (50, 'Complete'), (99, 'Failed')], default=20, verbose_name='Status')),
                ('identifier', models.CharField(default='not_set', max_length=255, verbose_name='Identifier')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Progress')),
                ('progress_output', jsonfield.fields.JSONField(default=list, dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, verbose_name='Progress output')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('execution_time', models.IntegerField(default=0, verbose_name='Execution time')),
                ('result', models.TextField(blank=True, default='', verbose_name='Result')),
                ('object_id', models.BigIntegerField(blank=True, null=True, verbose_name='Object ID')),
                ('object_verbose_name', models.TextField(blank=True, default='', verbose_name='Object name')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.ContentType', verbose_name='Object type')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Started by')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
