# Generated by Django 2.2.6 on 2019-10-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trionyx', '0010_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(10, 'Scheduled'), (20, 'Queue'), (30, 'Locked'), (40, 'Running'), (50, 'Completed'), (99, 'Failed')], default=20, verbose_name='Status'),
        ),
    ]
